name: Run Backend Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # This sets the environment where the tests will run (Ubuntu in this case)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set Django settings module and update PYTHONPATH
      - name: Set Django settings module and update PYTHONPATH
        run: |
          echo "DJANGO_SETTINGS_MODULE=code.server.core.settings" >> $GITHUB_ENV
          echo "PYTHONPATH=$(pwd)/code/server:$(pwd)" >> $GITHUB_ENV  # Add code/server to PYTHONPATH

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set the version of Python you're using

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

      # Step 5: Run tests with pytest
      - name: Run tests with pytest
        run: |
          pytest code/server/test/test_auth.py  # Run the test file at the correct path
